name: doctor_ai_assistent
description: "ECNX Ambient Listening"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # local storage
  shared_preferences: ^2.3.4

  # dependency injection
  get_it: ^8.0.3

  # navigation
  auto_route: ^9.2.2

  # design
  flutter_svg: ^2.0.16
  flutter_screenutil: ^5.9.3
  flutter_quill: ^10.8.5
  gif: ^2.3.0
  awesome_extensions: ^2.0.19
  mask_text_input_formatter: ^2.9.0
  syncfusion_flutter_datepicker: ^27.2.5

  # audio
  just_audio: ^0.9.42

  # state management
  provider: ^6.1.2
  record: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/gifs/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
